"""empty message

Revision ID: 33a77d52594f
Revises: ccb44fe7b066
Create Date: 2023-05-21 19:59:18.142868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a77d52594f'
down_revision = 'ccb44fe7b066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('cities_nation_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('cities_nation_key', ['nation'])

    # ### end Alembic commands ###
