"""empty message

Revision ID: 43e86e45a097
Revises: aa6ac1f92953
Create Date: 2023-05-21 19:55:51.322844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e86e45a097'
down_revision = 'aa6ac1f92953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=1580),
               existing_nullable=False)
        batch_op.alter_column('bending_abilities',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=580),
               type_=sa.String(length=1580),
               existing_nullable=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=580),
               existing_nullable=False)

    with op.batch_alter_table('furry__friends', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=580),
               existing_nullable=False)

    with op.batch_alter_table('previous__avatars', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=580),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('previous__avatars', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=580),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('furry__friends', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=580),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=580),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=1580),
               type_=sa.VARCHAR(length=580),
               existing_nullable=False)
        batch_op.alter_column('bending_abilities',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1580),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('nationality',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
