"""empty message

Revision ID: 92370e733b62
Revises: 
Create Date: 2023-05-22 15:37:46.643802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92370e733b62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bending__types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_relation', sa.String(length=120), nullable=False),
    sa.Column('nation_relation_sub', sa.String(length=120), nullable=True),
    sa.Column('abilities', sa.String(length=180), nullable=False),
    sa.Column('notable_benders', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nationality', sa.String(length=180), nullable=False),
    sa.Column('hair_color', sa.String(length=180), nullable=False),
    sa.Column('eye_color', sa.String(length=180), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('notable_traits', sa.String(length=380), nullable=False),
    sa.Column('bending_abilities', sa.String(length=180), nullable=False),
    sa.Column('photo', sa.String(length=1580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nation', sa.String(length=120), nullable=True),
    sa.Column('leader', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=580), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('furry__friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=580), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('species')
    )
    op.create_table('previous__avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nation', sa.String(length=120), nullable=True),
    sa.Column('hair_color', sa.String(length=180), nullable=False),
    sa.Column('eye_color', sa.String(length=180), nullable=False),
    sa.Column('age_at_death', sa.Integer(), nullable=False),
    sa.Column('notable_traits', sa.String(length=380), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nation')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('previous__avatars')
    op.drop_table('furry__friends')
    op.drop_table('cities')
    op.drop_table('character')
    op.drop_table('bending__types')
    # ### end Alembic commands ###
