"""empty message

Revision ID: aa6ac1f92953
Revises: 14dca60149df
Create Date: 2023-05-21 19:34:06.075976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6ac1f92953'
down_revision = '14dca60149df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bending__types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_relation', sa.String(length=120), nullable=False),
    sa.Column('nation_relation_sub', sa.String(length=120), nullable=True),
    sa.Column('abilities', sa.String(length=80), nullable=False),
    sa.Column('notable_benders', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nation_relation'),
    sa.UniqueConstraint('nation_relation_sub')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('bending_abilities', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nation', sa.String(length=120), nullable=True),
    sa.Column('leader', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nation')
    )
    op.create_table('furry__friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('species')
    )
    op.create_table('previous__avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nation', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=580), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previous__avatars')
    op.drop_table('furry__friends')
    op.drop_table('cities')
    op.drop_table('character')
    op.drop_table('bending__types')
    # ### end Alembic commands ###
