"""empty message

Revision ID: ccb44fe7b066
Revises: d4f5020f52a3
Create Date: 2023-05-21 19:58:27.669642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb44fe7b066'
down_revision = 'd4f5020f52a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bending__types', schema=None) as batch_op:
        batch_op.drop_constraint('bending__types_nation_relation_key', type_='unique')
        batch_op.drop_constraint('bending__types_nation_relation_sub_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bending__types', schema=None) as batch_op:
        batch_op.create_unique_constraint('bending__types_nation_relation_sub_key', ['nation_relation_sub'])
        batch_op.create_unique_constraint('bending__types_nation_relation_key', ['nation_relation'])

    # ### end Alembic commands ###
