"""empty message

Revision ID: ecc9d6a8a576
Revises: 33a77d52594f
Create Date: 2023-05-22 14:20:03.622104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc9d6a8a576'
down_revision = '33a77d52594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('age', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('notable_traits', sa.String(length=380), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('previous__avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('age', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('notable_traits', sa.String(length=380), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('previous__avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=580), autoincrement=False, nullable=False))
        batch_op.drop_column('notable_traits')
        batch_op.drop_column('age')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=1580), autoincrement=False, nullable=False))
        batch_op.drop_column('notable_traits')
        batch_op.drop_column('age')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
